services:
  user-db:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - user_data:/var/lib/postgresql/data

  user-services:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user_service_container
    restart: always
    depends_on:
      - user-db
    env_file:
      - ./user-service/.env
    ports:
      - "8000:8000"
  
  

volumes:
  user_data:
